### ISSUE TITLE
Authentication for Jupyterhub

### ISSUE THREAD

**Issue by arokem** [dask/dask-gateway#191]
@yuvipanda and I were trying to follow [these](https://gateway.dask.org/install-kube.html#authenticating-with-jupyterhub) to authenticate with Jupyterhub on a hub deployed with kubernetes to GCP.  This did not work, because we kept getting a 404 for any attempt to interact with the Gateway.

**Comment by jcrist** [comment]
What helm configuration were you using? What client configuration are you using? Are you deploying dask-gateway as a service behind JupyterHub's proxy (e.g. a url is specified in `hub.services.dask-gateway`), or as a standalone service?

**Comment by arokem** [comment]
Hey @jcrist : thanks for the quick response! 

The configuration is here: https://github.com/learning-2-learn/l2lhub-deployment/tree/staging/deployments/l2lhub/config 

The secrets config for staging (scrubbed of secrets) is as follows: 

```
dask-gateway:
    gateway:
      proxyToken: XXX
    auth:
      type: jupyterhub
      jupyterhub:
        apiToken: "XXX"

jupyterhub:
  hub:
    cookieSecret: XXX
    services:
        dask-gateway:
          apiToken: "XXX"
  proxy:
    secretToken: XXX
  auth:
    type: github
    github:
      clientId: "XXX"
      clientSecret: "XXX
      callbackUrl: "http://XXX/hub/oauth_callback"
      org_whitelist:
        - "learning-2-learn"
    scopes:
      - "read:user"
    admin:
      access: true
      users:
        - arokem
        - jhamman
        - yuvipanda
```

We tried this both as a service behind the JHub proxy and as a standalone. Both produced 404s.
