### ISSUE TITLE
Default tolerations on dask kubernetes workers

### ISSUE THREAD

**Issue by scottyhq** [dask/dask-gateway#220]
I was just trying out dask-gateway for the first time coming from dask-kubernetes and wasn't getting workers to launch on existing nodegroups. Seems that the pods coming from dask-gateway only have the `k8s.dask.org_dedicated` toleration, but dask-kubernetes pods also have `k8s.dask.org/dedicated`

reason for both https://github.com/dask/dask-kubernetes/blob/b88ebb1f596ffd7b91299191e51fcd7b1df98a29/dask_kubernetes/objects.py#L223-L226 : “GKE currently does not permit creating taints on a node pool
        # with a `/` in the key field” 

An easy fix is adding both taints to worker nodes, but I'm not sure why both tolerations don't show up on the gateway pods...

`dask-gateway-scottyhq-worker-403c50c64a2e41c59257fadf513266a1`
```
 tolerations:
  - key: k8s.dask.org_dedicated
    operator: Equal
    value: worker
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
```

versus a KubeCluster pod `dask-scottyhq-7eda3809-3b59nd`
```
  tolerations:
  - effect: NoSchedule
    key: k8s.dask.org/dedicated
    operator: Equal
    value: worker
  - effect: NoSchedule
    key: k8s.dask.org_dedicated
    operator: Equal
    value: worker
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
```
