### ISSUE TITLE
Prefix config in 0.7.0, dask-gateway-server won't serve under it

### ISSUE THREAD

**Issue by consideRatio** [dask/dask-gateway#239]
It is possible to configure a prefix in the Helm chart. But I think the dask-gateway-server binary running in `deploy/api-<release>` isn't getting configured to expect receiving such traffic from `deploy/traefik-<release>`.

## Example

The JupyterHub Helm chart allow us to register a JupyterHub service through its configuration. During this registration, we can configure `url` that will make JupyterHub configure its proxy to route `/services/<service-name>` to that url for us. This way we can reuse JupyterHub's proxy's ability to manage HTTPS traffic and remain on the same domain etc.

#### jupyterhub/config.yaml (Helm values)
```yaml
hub:
  services:
    # ref: https://jupyterhub.readthedocs.io/en/stable/reference/services.html#properties-of-a-service
    dask-gateway:
      apiToken: "redacted"
      url: http://traefik-dask-gateway.dask-gateway
```

#### dask-gateway/config.yaml (Helm values)
```yaml
gateway:
  loglevel: INFO
  # Path prefix to serve dask-gateway api requests under
  # This prefix will be added to all routes the gateway manages
  # in the traefik proxy.
  prefix: /services/dask-gateway
```

## Issue summary

From logs to deploy/api I can see that it receives traffic if I curl `myhub.com/services/dask-gateway/api/version` to the path `/services/dask-gateway/api/version`, but it return 404 to it but responds properly to `/api/version`. So, the `gateway.prefix` config seem only to configure treafik to direct traffic properly, but fail to configure the dask-gateway-server binary in `deploy/api` to expect traffic on that path.

```
(base) ➜  jupyterhub git:(master) ✗ kubectl logs -n dask-gateway deploy/api-dask-gateway
[I 2020-04-09 10:49:03.515 DaskGateway] Starting dask-gateway-server - version 0.7.0
[I 2020-04-09 10:49:03.793 DaskGateway] Authenticator: 'dask_gateway_server.auth.JupyterHubAuthenticator'
[I 2020-04-09 10:49:03.794 DaskGateway] Backend: 'dask_gateway_server.backends.kubernetes.backend.KubeBackend'
[I 2020-04-09 10:49:03.819 DaskGateway] Dask-Gateway server started
[I 2020-04-09 10:49:03.820 DaskGateway] - Private API server listening at http://:8000
[I 2020-04-09 10:49:14.516 DaskGateway] 404 GET /services/dask-gateway/api/version 0.661ms
[I 2020-04-09 10:54:51.444 DaskGateway] 200 GET /api/version 0.646ms
```

## Questions

- Is there a configuration that we can write to the configuration of dask-server-gateway that would help it serve content under the prefix?
- We could also make traefik rewrite the path to `/` before sending traffic onwards to the dask-gateway-server, but sometimes applications needs to know where the client is accessing it from. If this is the case dask-gateway-server, this is a bad option.
