### ISSUE TITLE
Release 0.7.1

### ISSUE THREAD

**Issue by jcrist** [dask/dask-gateway#243]
There's been a few quick bugfixes in the last day, I'd like to get a bugfix release (0.7.1) out soon (probably early next week) with these updates.

- #242 
- #241 

I think I'd like to get #234 in this release as well if possible.

Are there any other quick pressing issues we should get in before releasing?

**Comment by jcrist** [comment]
cc @gforsyth.

@TomAugspurger  and @consideratio, if you're able to install from master, it might be useful to try and see if anything else comes up (no worries if you can't/you're busy).

**Comment by jcrist** [comment]
#234 is now in.

**Comment by consideRatio** [comment]
@jcrist I got past the previous issues but I ran into an issue that I had trouble debugging.

#### `!cat /etc/dask/gateway.yaml`

```yaml
# ref: https://gateway.dask.org/configuration-user.html
# ref: https://docs.dask.org/en/latest/configuration.html

gateway:
  # The full address to the dask-gateway server.
  address: https://jupyter.example.com/services/dask-gateway

  auth:
    type: jupyterhub
    jupyterhub:
      apiUrl: https://jupyter.example.com/hub/api
      # apiUrl: http://hub.jupyterhub:8081/hub/api
```

#### `kubectl logs deploy/api-dask-gateway`
```
[I 2020-04-10 16:35:02.857 DaskGateway] 401 GET /api/v1/clusters/ 0.729ms
[I 2020-04-10 16:35:02.900 DaskGateway] 200 GET /api/v1/clusters/ 37.421ms
[I 2020-04-10 16:35:05.506 DaskGateway] 401 GET /api/v1/options 1.004ms
[I 2020-04-10 16:35:05.540 DaskGateway] 200 GET /api/v1/options 28.512ms
[I 2020-04-10 16:35:07.226 DaskGateway] 401 POST /api/v1/clusters/ 0.912ms
[I 2020-04-10 16:35:07.262 DaskGateway] Creating cluster dask-gateway.a407df26ecd94a6d8a98a88c65471281 for user erik.sundell@example.com
[I 2020-04-10 16:35:07.275 DaskGateway] 201 POST /api/v1/clusters/ 43.551ms
[I 2020-04-10 16:35:09.950 DaskGateway] 200 GET /api/v1/clusters/dask-gateway.a407df26ecd94a6d8a98a88c65471281?wait 2669.508ms
[I 2020-04-10 16:35:09.958 DaskGateway] 204 DELETE /api/v1/clusters/dask-gateway.a407df26ecd94a6d8a98a88c65471281 0.850ms
```

#### `cluster = gateway.new_cluster(options)`
```
---------------------------------------------------------------------------
GatewayClusterError                       Traceback (most recent call last)
<ipython-input-4-588fddc048cd> in <module>
----> 1 cluster = gateway.new_cluster(options)

/tmp/dask-gateway/dask-gateway/dask_gateway/client.py in new_cluster(self, cluster_options, shutdown_on_close, **kwargs)
    623             cluster_options=cluster_options,
    624             shutdown_on_close=shutdown_on_close,
--> 625             **kwargs,
    626         )
    627 

/tmp/dask-gateway/dask-gateway/dask_gateway/client.py in __init__(self, address, proxy_address, auth, cluster_options, shutdown_on_close, asynchronous, loop, **kwargs)
    780             shutdown_on_close=shutdown_on_close,
    781             asynchronous=asynchronous,
--> 782             loop=loop,
    783         )
    784 

/tmp/dask-gateway/dask-gateway/dask_gateway/client.py in _init_internal(self, address, proxy_address, auth, cluster_options, cluster_kwargs, shutdown_on_close, asynchronous, loop, name)
    872             self.status = "starting"
    873         if not self.asynchronous:
--> 874             self.gateway.sync(self._start_internal)
    875 
    876     @property

/tmp/dask-gateway/dask-gateway/dask_gateway/client.py in sync(self, func, *args, **kwargs)
    326             )
    327             try:
--> 328                 return future.result()
    329             except BaseException:
    330                 future.cancel()

/opt/conda/lib/python3.6/concurrent/futures/_base.py in result(self, timeout)
    430                 raise CancelledError()
    431             elif self._state == FINISHED:
--> 432                 return self.__get_result()
    433             else:
    434                 raise TimeoutError()

/opt/conda/lib/python3.6/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

/tmp/dask-gateway/dask-gateway/dask_gateway/client.py in _start_internal(self)
    886             self._start_task = asyncio.ensure_future(self._start_async())
    887         try:
--> 888             await self._start_task
    889         except BaseException:
    890             # On exception, cleanup

/tmp/dask-gateway/dask-gateway/dask_gateway/client.py in _start_async(self)
    904         # Connect to cluster
    905         try:
--> 906             report = await self.gateway._wait_for_start(self.name)
    907         except GatewayClusterError:
    908             raise

/tmp/dask-gateway/dask-gateway/dask_gateway/client.py in _wait_for_start(self, cluster_name)
    558                     raise GatewayClusterError(
    559                         "Cluster %r failed to start, see logs for "
--> 560                         "more information" % cluster_name
    561                     )
    562                 elif report.status is ClusterStatus.STOPPED:

GatewayClusterError: Cluster 'dask-gateway.94c9c184f1634f2e95c1518df40436c1' failed to start, see logs for more information
```

#### `kubectl get daskclusters.gateway.dask.org`

It seems that the DELETE request logged in deploy/api didn't lead to the deletion of the daskcluster k8s resource btw.

```
NAME                               AGE
94c9c184f1634f2e95c1518df40436c1   4m
```

#### `kubectl logs deploy/traefik-dask-gateway`
```
time="2020-04-09T15:23:24Z" level=info msg="Configuration loaded from flags."
```

#### K8s events?
There are no events associated with the DaskCluster k8s resource either.

## Noteworthy

I had configured maximum clusters per user.

```yaml
gateway:
  # ref: https://gateway.dask.org/install-kube.html#using-extraconfig
  extraConfig:
    user-resource-limits: |
      # ref: https://gateway.dask.org/resource-limits.html
      c.UserLimits.max_clusters = 1
      c.UserLimits.max_cores = 32
      c.UserLimits.max_memory = str(3.45 * c.UserLimits.max_cores) + " GB"
```

Perhaps that was enforced by deploy/api, but I'd get multiple abandoned DaskCluster k8s resources. Also, a subsequent call to `gateway.list_clusters()` would return `[]`.

## Debugging advice
I've not successfully setup a local dev environment, instead I've modified `skaffold.yaml` to tag images as consideratio/... instead of `daskgateway/...`, pushed them to my dockerhub account, and then installed the helm chart from a git clone of master. When working against the dask-gateway-server I've worked from an environment where I git clone dask/dask-gateway and `pip install -e .` on the dask-gateway Python package.

At this point, we need logs for how the `report = await self.gateway._wait_for_start(self.name)` line failed, but I don't know how to get them.
