### ISSUE TITLE
Implicit proxy_address from address without explicit port fails to conclude :80 / :443 should be used.

### ISSUE THREAD

**Issue by consideRatio** [dask/dask-gateway#251]
It seems that we need to explicitly specify proxy_address in order to ensure it gets the port value explicitly set. If we don't cluster.get_client() fails.

**Comment by jcrist** [comment]
I'm unable to reproduce, can you provide an example init of a `Gateway` where the `proxy_address` attribute ends up without a port? Since no api calls are made on init, this should be doable without any infrastructure.

**Comment by consideRatio** [comment]
```yaml
# /etc/dask/gateway.yaml
gateway:
  address: http://traefik-dask-gateway.dask-gateway/services/dask-gateway
  # the correct proxy_address should be automatically inferred from `address` above,
  # but could also be configured explicitly as
  # proxy-address: gateway://traefik-dask-gateway.dask-gateway:80
  public-address: https://jupyter.example.com/services/dask-gateway

  auth:
    type: jupyterhub
    jupyterhub:
      apiUrl: http://hub.jupyterhub:8081/hub/api
```


```python
from dask_gateway import Gateway
gateway = Gateway() # errors later on cluster.get_client
# gateway = Gateway(proxy_address="gateway://traefik-dask-gateway.dask-gateway:80") # works

cluster = gateway.new_cluster()
cluster

# this is at risk crashing with an attempted connect to
# gateway://traefik-dask-gateway.dask-gateway
# without the port :80
client = cluster.get_client()
client
```

The error is:

```
```

---

Omg... I fail to reproduce it now. I'm not sure what caused this initially, I tried to ensure there were no lingering state that would influence this but perhaps I got it wrong. I assume I had failed to clear a ~/.config/dask/gateway.yaml before running these tests, drawing the wrong conclusions.
