### ISSUE TITLE
Add standard mapping option for environment variables.

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask-gateway#268]
In our Pangeo deployments, we have a need for setting an environment variable on the workers based on user input. This seems like the kind of thing that would be useful for all backends so I'm raising this here while we'll implement it on our own in Pangeo for now.

1. A widget / traitlet for accepting input from the user in the form of a mapping from `{name: value}`.
2. A standard dask-gateway config for this option for all backends supported by dask-gateway, which is then forwarded to the appropriate location.

The main downside I see with 2 is that this would make two ways to specify environment variables for each backend. The "dask-gateway" way, and the backend-native way. For kubernetes that would be

```yaml
gateway:
  backend:
    worker:
      extraContainerConfig:
        env:
          - name: name
            value: value
```

Is that problematic?

cc @rsignell-usgs and @scottyhq.
