### ISSUE TITLE
Support TLS for IngressRoute

### ISSUE THREAD

**Issue by eyal-lantzman** [dask/dask-gateway#298]
When Dask Gateway is hosted in a secure corporate environment (that prohibits accessing the dashboard via http), we still want to provide that ability to the users.
At the minimum, be able to support the follow generated route:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
....
spec:
  entryPoints:
  - websecure
  tls:
    options: 
      domains:
      - main: eyal-dask-cpu.812896951795.dev.aws.jpmchase.net
   routes:
     - kind: Rule
...
```
