### ISSUE TITLE
YAML parse error when specifying nodeSelector, affinity, or tolerations for traefik deployment

### ISSUE THREAD

**Issue by ncalandra** [dask/dask-gateway#307]
YAML parse error when specifying nodeSelector, affinity, or tolerations for traefik deployment. If any values are provided for these options, helm fails with:
```
Error: YAML parse error on dask-gateway/templates/traefik/deployment.yaml: error converting YAML to JSON: yaml: line 72: did not find expected '-' indicator
```

To test I updated the `values.yaml` file to include the following:

```yaml
# Configuration for the traefik proxy
traefik:
  # Settings for nodeSelector, affinity, and tolerations for the traefik pods
  nodeSelector:
    testKey: testValue
  affinity:
    testKey: testValue
  tolerations:
    - test
```

The fix for this is to reduce the indentation of everything [below this line]( https://github.com/dask/dask-gateway/blob/master/resources/helm/dask-gateway/templates/traefik/deployment.yaml#L87).  It should be at the same level of the `containers` key.
