### ISSUE TITLE
How to Authenticate Using Basic Auth in Dask-Gateway?

### ISSUE THREAD

**Issue by rileyhun** [dask/dask-gateway#342]
I added an environmental variable (the password) to a docker file, and then in the helm chart, I reference the environmental variable like so:

```
  auth:
    # The auth type to use. One of {simple, kerberos, jupyterhub, custom}.
    type: simple

    simple:
      # A shared password to use for all users.
      password: $DASK_GATEWAY_PASSWORD
```

Now when I try to establish a connection and invoke BasicAuth, it still says I'm unauthorized. 

```
auth = BasicAuth(os.environ['DASK_GATEWAY_PASSWORD'])
gateway = Gateway(
    address=os.environ['IP_ADDRESS'],
    auth=auth
)
```

**What happened**:
I cannot establish a connection w/ Dask Gateway when I enter BasicAuth information; I get the following error:

`ClientResponseError: 401, message='Unauthorized'`

**Anything else we need to know?**:
I am using an internal load balancer on GCP to expose the proxy server. When I wasn't using the simple authenticator, there were no issues establishing a connection to Dask Gateway

**Environment**:

- Dask-Gateway-Server version: latest
- Python version: 3.7.8
