### ISSUE TITLE
How to make Traefik Proxy an Ingress?

### ISSUE THREAD

**Issue by rileyhun** [dask/dask-gateway#351]
I want to make the traefik proxy an ingress so that I can add cloud armor and IAP. In the config yaml file, I made the service type for the traefik proxy `nodePort`. Then I deployed an ingress using the following manifest:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dask-gateway-proxy-ingress
  namespace: dask-gateway
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "dask-gateway-proxy-static-ip"
spec:
  backend:
    serviceName: traefik-dask-gateway
    servicePort: 80
```

Doing so returns a health check error:
 
```
All backend services are in UNHEALTHY state. 
```

I think to bypass this health check we need a liveness/readiness probe for the Traefik Proxy since the traefik proxy doesn't return a 200 response status?

Thanks,

Riley
