### ISSUE TITLE
Helm chart: "imagePullSecrets" missing for backend

### ISSUE THREAD

**Issue by erl987** [dask/dask-gateway#375]
Both `gateway` and `controller` have an option to specify `imagePullSecrets` in the `values.yaml` file of `dask-gateway`. This is however missing for `backend`.

I think that this is much more important for the backend because it will often be customized? The cloud provider I am using is by default controlling the access to the image repository by a Kubernetes secret.

So, I would appreciate if this missing configuration could be added.

Any suggestions on how I can work around this in the meanwhile?

/Ralf

**Comment by erl987** [comment]
Ok, a workaround is to use `extraPodConfig`:

```
dask-gateway:
  gateway:
    backend:
      scheduler:
        extraPodConfig:
          imagePullSecrets:
            - name: default-secret
```

In similar way this is to be done for the worker.
