### ISSUE TITLE
External load balancer for traefik server is ignored

### ISSUE THREAD

**Issue by erl987** [dask/dask-gateway#379]
# Environment:
* dask-gateway: `0.8.0`
* helm: `version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}`
* kubectl: `Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-r0-CCE20.8.1.3.B001-17.36.5", GitCommit:"d61c11191a704802f93e5d86877a8fcffe208d58", GitTreeState:"clean", BuildDate:"2020-10-16T09:38:58Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`
* OS: `Debian 10`

# Bug:
Defining an external load balancer for the `traefik` service has no effect.

# Steps to reproduce:

* `values.yaml`
  ```
  gateway:
    image:
      name: ###.###.###.###:#####/daskgateway/dask-gateway-server
      tag: 0.8.0
  
    imagePullSecrets:
      - name: default-secret
  
  controller:
    image:
      name: ###.###.###.###:#####/daskgateway/dask-gateway-server
      tag: 0.8.0
  
    imagePullSecrets:
      - name: default-secret
  
  traefik:
    replicas: 1
  
    # required for OTC
    service:
      type: LoadBalancer
      annotations:
        kubernetes.io/elb.class: union
        kubernetes.io/elb.id: ########-####-####-####-###########
      spec:
        loadBalancerIP: ##.##.##.##
      ports:
        web:
          # The port HTTP(s) requests will be served on
          port: 80
          nodePort: null
        tcp:
          # The port TCP requests will be served on. Set to `web` to share the
          # web service port
          port: web
          nodePort: null
  ```
  Note that the load balancer depends on your configuration. In this case, it is a load balancer in the Open Telekom Cloud (which requires this external creation of a load balancer).

* run:
  ```
  $ helm repo add daskgateway https://dask.org/dask-gateway-helm-repo/
  $ helm repo update
  $ helm install --version 0.8.0 grey-november daskgateway/dask-gateway --dry-run --debug
  ```
* inspect the generated `yaml`-files, you get for the *traefik service* the following:
  ```
  apiVersion: v1
  kind: Service
  metadata:
    name: traefik-grey-november-dask-gateway
    labels:
      app.kubernetes.io/name: dask-gateway
      helm.sh/chart: dask-gateway-0.8.0
      app.kubernetes.io/instance: grey-november
      app.kubernetes.io/version: "0.8.0"
      app.kubernetes.io/managed-by: Helm
      gateway.dask.org/instance: grey-november-dask-gateway
  spec:
    type: LoadBalancer
    selector:
      app.kubernetes.io/name: dask-gateway
      app.kubernetes.io/instance: grey-november
      app.kubernetes.io/component: traefik
    ports:
      - name: web
        targetPort: 8000
        port: 80
  ```

* the expected output is:
  ```
  apiVersion: v1
  kind: Service
  metadata:
    name: traefik-grey-november-dask-gateway
    labels:
      app.kubernetes.io/name: dask-gateway
      helm.sh/chart: dask-gateway-0.8.0
      app.kubernetes.io/instance: grey-november
      app.kubernetes.io/version: "0.8.0"
      app.kubernetes.io/managed-by: Helm
      gateway.dask.org/instance: grey-november-dask-gateway
    annotations:
      kubernetes.io/elb.class: union
      kubernetes.io/elb.id: ########-####-####-####-###########
  spec:
    type: LoadBalancer
    selector:
      app.kubernetes.io/name: dask-gateway
      app.kubernetes.io/instance: grey-november
      app.kubernetes.io/component: traefik
    loadBalancerIP: ##.##.##.##
    ports:
      - name: web
        targetPort: 8000
        port: 80
  ```
  
  Interestingly the correct behavior is obtained if deploying the Helm chart instead within a subchart (just modify the code in #377 to also contain this load balancer).
