### ISSUE TITLE
JupyterHub apiUrl detection fails with hub.baseUrl is set

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask-gateway#383]
The Jupyterhub helm chart includes a `hub.baseUrl` for serving the hub under a path other than `/`, e.g. `/jupyter/`. I believe this breaks the automatic API setting at https://github.com/dask/dask-gateway/blob/7d1659db8b2122d1a861ea820a459fd045fc3f02/resources/helm/dask-gateway/templates/gateway/configmap.yaml#L97.

I'm not sure if the `baseUrl` is available where that code is running, so it may be hard to detect the url automatically.

The workaround is to explicitly set the URL

```yaml
gateway:
  auth:
    jupyterhub:
      apiUrl: http://proxy-http:8000/jupyter/hub/api
```
