### ISSUE TITLE
Helm chart: Package a values.schema.json file with the chart to provide end user config validation logic

### ISSUE THREAD

**Issue by consideRatio** [dask/dask-gateway#418]
Helm 3 supports schema validation of configuration options for any users of a Helm chart that has a `values.schema.json` bundled with it.

In the JupyterHub Helm chart, we now ship such `values.schema.json` file with the Helm chart, but we maintain our schema via a schema.yaml file still because Yaml is far more convenient than JSON due to anchors etc.

With such schema, I bet almost all users of the Helm chart end up benefiting at some point because the validation logic will make a `helm upgrade` fail directly with a clear error message if something is misconfigured by mistake.

Imagine you for example passed this configuration.

```yaml
backend:
  scheduler:
    extraPodConfig:
      serviceAccountName: cloud-user-sa
  worker:
    extraPodConfig:
      serviceAccountName: cloud-user-sa
```

Then you would get an error like...

```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
dask-gateway:
- (root): Additional property backend is not allowed
```

This is because the correct configuration is actually, and the schema had no entry about `backend` being passed anywhere else than under `gateway`.

```yaml
gateway:
  backend:
    scheduler:
      extraPodConfig:
        serviceAccountName: cloud-user-sa
    worker:
      extraPodConfig:
        serviceAccountName: cloud-user-sa
```

Here is a PR in the JupyterHub Helm chart adding such schema for example. You can also trial use of such schema by the following one-liner.

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2033

```shell
helm template jupyterhub --repo https://jupyterhub.github.io/helm-chart/ --set=hub.faultyConfig=asdf

Error: values don't meet the specifications of the schema(s) in the following chart(s):
jupyterhub:
- hub: Additional property faultyConfig is not allowed
```
