### ISSUE TITLE
Dask Traefik Proxy Exposed as ClusterIP. Separate Traefik2 Ingress Points to the Traefik Proxy Service

### ISSUE THREAD

**Issue by anyaddres** [dask/dask-gateway#457]
**What happened**:
Set dask service type to be ClusterIP
```
  service:
      type: ClusterIP
      annotations: {}
      spec: {}
      ports:
        web:
          port: 80
          nodePort: null
        tcp:
          # The port TCP requests will be served on. Set to `web` to share the
          # web service port
          port: web
          nodePort: null
```
From the Client side tried to create a cluster and then get a client. 

```
Timed out trying to connect to gateway://common-dask-test.int.somename.com:80/dask-common-test.5cdfc65644e644b08eae895132d63caa after 30 s
```

**What you expected to happen**:
Get a client reference back. 
**Minimal Complete Verifiable Example**:

```python
auth is BasicAuth
g = Gateway('http://common-dask-test.somename.com', auth=auth)
c = g.new_cluster(shutdown_on_close=False)
client = c.get_client()
```

**Anything else we need to know?**:
Dask is installed using Helm Chart
```
RELEASE=dask-gateway-test
NAMESPACE=data-common-test
VERSION=0.9.0

helm upgrade --install \
    --namespace $NAMESPACE \
    --version $VERSION \
    --values ./overrides-values.yaml \
    $RELEASE \
    daskgateway/dask-gateway
```
**Environment**:
K8s. 1.17 EKS

- Dask version: 
-

```
dask==2021.7.2
dask-gateway==0.9.0
distributed==2021.7.2
```
On both dask cluster image and the local client. 
- Python version: 3.10
- Operating System: Linux
- Install method (conda, pip, source): pip
