### ISSUE TITLE
Setting parameters for Dask Distributed when deploying Dask Gateway

### ISSUE THREAD

**Issue by LewisJarrod** [dask/dask-gateway#560]
Hello, I’d like to set some of the parameters as described in the [Dask Distributed](https://docs.dask.org/en/latest/configuration.html) docs such as worker spill and allow-failures but don’t know if its possible to set these variables when using the [Dask Gateway](https://github.com/dask/dask-gateway/tree/main/resources/helm/dask-gateway) helm charts

I have tried using `dask.config.set({..})` from the calling code but I found that the configuration does not carry over. I also haven’t had any success trying to set the configuration using env vars such as `DASK_DISTRIBUTED__SCHEDULER__ALLOWED_FAILURES`

Snippet from values.yaml
```
dask-gateway:
  gateway:
    backend:
      scheduler:
        extraContainerConfig:
          env:
            - name: DASK_DISTRIBUTED__SCHEDULER__ALLOWED_FAILURES
              value: "20"
            - name: DASK_DISTRIBUTED__WORKER__MEMORY__SPILL
              value: "0.9"
      worker:
        extraContainerConfig:
          env:
            - name: DASK_DISTRIBUTED__SCHEDULER__ALLOWED_FAILURES
              value: "20"
            - name: DASK_DISTRIBUTED__WORKER__MEMORY__SPILL
              value: "0.9"
```
