### ISSUE TITLE
Helm chart: node configuration missing for scheduler and worker

### ISSUE THREAD

**Issue by meghnaghadge** [dask/dask-gateway#587]
Not able to Set nodeSelector, affinity, and tolerations for the scheduler and worker pods.
I try to apply below code for scheduler and worker in values.yaml but not working.

```
      # Settings for nodeSelector, affinity, and tolerations for the worker pods
       nodeSelector:
         Key: value
      affinity: {}
      tolerations:
        - key: "key"
          operator: "Equal/Exist"
          value: "value"
          effect: "NoSchedule"

```
but got error as below:

```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
dask-gateway:
- gateway.backend.scheduler: Additional property nodeSelector is not allowed
- gateway.backend.scheduler: Additional property tolerations is not allowed
- gateway.backend.scheduler: Additional property affinity is not allowed
- gateway.backend.worker: Additional property affinity is not allowed
- gateway.backend.worker: Additional property nodeSelector is not allowed
- gateway.backend.worker: Additional property tolerations is not allowed
```

Any suggestions on how I can use node settings for scheduler and worker in dask gateway helm chart?

**Comment by jacobtomlinson** [comment]
Are you setting those values in the `extraPodConfig`?

https://gateway.dask.org/install-kube.html#using-extrapodconfig-extracontainerconfig

```yaml
gateway:
  backend:
    worker:
      extraPodConfig:
        # Settings for nodeSelector, affinity, and tolerations for the worker pods
        nodeSelector:
          Key: value
        affinity: {}
        tolerations:
          - key: "key"
            operator: "Equal/Exist"
            value: "value"
            effect: "NoSchedule"
```

**Comment by meghnaghadge** [comment]
Hey @jacobtomlinson, thanks for reply.
Yes I tried putting node configuration under extraPodConfig but not working for me. 
Getting below error:
`HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod in version \"v1\" cannot be handled as a Pod: v1.Pod.Spec: v1.PodSpec.NodeSelector: ReadString: expects \" or n, but found {, error found in #10 byte of ...|finity\": {}, \"node-p|..., bigger context ...|tifact-registry\"}], \"nodeSelector\": {\"affinity\": {}, \"key\": \"value\"}, \"tolerations\": [{\"ef|...","reason":"BadRequest","code":400}
`

below my code in helm chart
```
gateway:
  backend:  
    scheduler:  
      extraPodConfig:
        # Settings for nodeSelector, affinity, and tolerations for the scheduler pods
        nodeSelector:
          key: value
          affinity: {}
        tolerations:
          - key: "key"
            operator: "Equal"
            value: "value"
            effect: "NoSchedule"
```
