### ISSUE TITLE
 Adding envs key Helm values to gateway resources #688 

### ISSUE THREAD

**Issue by JoeJasinski** [dask/dask-gateway#689]
Currently, one of the configuration mechanisms of the dask gateway Helm chart is to use the extraConfig to provide python code that configures the gateway, using the Traitlet syntax. This is extremely powerful; however, as that configuration grows in size, the difference between configuration and code blurs and it becomes more difficult to override individual settings. 

It would be valuable to set the overall configuration using Python code, but pass in environment variables to be used within that configuration. That way, there could be a clear separate between configuration and code and the environment variables will make it easier to tune a particular setting. 

I think this feature is best described through this example:

```yaml
gateway:
  envs:
  - name: IDLE_TIMEOUT
    value: "500"
  extraConfig:
    # Note that the key name here doesn't matter. Values in the
    # `extraConfig` map are concatenated, sorted by key name.
    clusteroptions: |
      import os
      idle_timeout =  int(os.environ.get("IDLE_TIMEOUT", 300))
      cluster_max_memory = os.environ.get("CLUSTER_MAX_MEMORY", "20G")
      c.KubeClusterConfig.idle_timeout = idle_timeout
      c.KubeClusterConfig.cluster_max_memory = cluster_max_memory
```
I've made an MR with what I believe will make this change. Let me know if you think this would be a useful feature. 

https://github.com/dask/dask-gateway/pull/688
